# 07 Phase 1/2 예측 실험

**논문 실험 설계** — 40개 조건 × 10개 알고리즘(Phase 1) → 조건별 Best × 6 임베딩(Phase 2)

| 축 | 조건 수 | 클러스터 기준 |
|----|--------|--------------|
| ML | 5 type × 4 cluster = **20** | TS2Vec+KMeans (`ML_CLUSTER`) |
| SBC | 5 type × 4 cluster = **20** | Rule-based (`SBC_CLUSTER`) |
| **합계** | **40** | |

**Phase 1 (10알고리즘):** ARIMA, Prophet, SBA, TSB, RF, XGBoost, LSTM, Autoformer, N-HiTS, iTransformer  
**Phase 2 (6 하이브리드):** Phase1 Best + PCA / FastDTW / AE / GAF-CNN / TS2Vec / PatchTST  
**지표:** WMAPE | **검증:** 201731–201733 (3주)

### ⓪ 환경 설정 및 데이터 병합

주간 데이터에 SBC·ML 클러스터 라벨을 붙이고, Phase 1/2 실험 유틸을 로드합니다.

In [1]:
import sys
from pathlib import Path
import pandas as pd

NOTEBOOK_DIR = Path.cwd()
REPO_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name == 'code' else NOTEBOOK_DIR
sys.path.insert(0, str(REPO_ROOT / 'code'))

from utils.paths import DATA_PROCESSED, SBC_CLUSTER, ML_CLUSTER
from utils.splits import VAL_WEEKS, TRAIN_WEEK_MAX
from utils.device import device_label
from utils.phase_experiments import (
    PHASE1_MODELS, EMBEDDING_NAMES,
    run_phase1_all, summarize_phase1,
    build_global_embedding_cache,
    run_phase2_all, summarize_phase2,
)

print('Torch device:', device_label())

# 주간 데이터 + 피처 + 클러스터 라벨 병합
df = pd.read_parquet(DATA_PROCESSED / 'df_weekly.parquet')
feat_path = DATA_PROCESSED / 'df_weekly_features.parquet'
feat_df = pd.read_parquet(feat_path) if feat_path.exists() else df.copy()
sbc = pd.read_parquet(SBC_CLUSTER)
ml = pd.read_parquet(ML_CLUSTER)

for d in (df, feat_df):
    d.drop(columns=[c for c in d.columns if c in ('SBC_CLUSTER', 'ML_CLUSTER')], errors='ignore', inplace=True)

cl_sbc = sbc[['type', 'family', 'SBC_CLUSTER']]
cl_ml = ml[['type', 'family', 'ML_CLUSTER', 'embedding_method', 'clustering_method']]
df = df.merge(cl_sbc, on=['type', 'family'], how='left')
df = df.merge(cl_ml, on=['type', 'family'], how='left')
feat_df = feat_df.merge(cl_sbc, on=['type', 'family'], how='left')
feat_df = feat_df.merge(cl_ml, on=['type', 'family'], how='left')

print('시계열:', df.groupby(['type', 'family']).ngroups)
print('ML 클러스터링:', ml['embedding_method'].iloc[0], '+', ml['clustering_method'].iloc[0])
print('Phase1 알고리즘:', len(PHASE1_MODELS), '개 | Phase2 임베딩:', len(EMBEDDING_NAMES), '개')
print('학습 <=', TRAIN_WEEK_MAX, '| 검증:', VAL_WEEKS)

Torch device: cpu
시계열: 165
ML 클러스터링: TS2Vec + KMeans
Phase1 알고리즘: 10 개 | Phase2 임베딩: 6 개
학습 <= 201730 | 검증: [201731, 201732, 201733]

### ① Phase 1 — 40조건 × 10알고리즘

각 **type×cluster** 조건(20 SBC + 20 ML)에서 10개 알고리즘을 독립 실행하고, 조건별 평균 WMAPE로 Best를 선정합니다.

> DL 모델은 연산량 절감을 위해 epoch=40 적용. 전체 실행에 수십 분~수 시간 소요될 수 있습니다.

In [2]:
# Phase 1: SBC 20조건 + ML 20조건 (이미 실행됐으면 캐시 로드)
p1_path = DATA_PROCESSED / 'phase1_results.parquet'
if p1_path.exists():
    phase1 = pd.read_parquet(p1_path)
    phase1_summary = pd.read_csv(DATA_PROCESSED / 'phase1_summary.csv')
    phase1_best = pd.read_csv(DATA_PROCESSED / 'phase1_best_per_condition.csv')
    print('Phase1 캐시 로드 | rows:', len(phase1))
else:
    phase1_sbc = run_phase1_all(df, feat_df, cluster_col='SBC_CLUSTER', cluster_scheme='SBC')
    phase1_ml = run_phase1_all(df, feat_df, cluster_col='ML_CLUSTER', cluster_scheme='ML')
    phase1 = pd.concat([phase1_sbc, phase1_ml], ignore_index=True)
    phase1_summary, phase1_best = summarize_phase1(phase1)
    phase1.to_parquet(p1_path, index=False)
    phase1_summary.to_csv(DATA_PROCESSED / 'phase1_summary.csv', index=False)
    phase1_best.to_csv(DATA_PROCESSED / 'phase1_best_per_condition.csv', index=False)
    print('Phase1 완료 | rows:', len(phase1))
phase1_best.sort_values(['cluster_scheme', 'type', 'cluster'])

Phase1 캐시 로드 | rows: 3300

   cluster_scheme type  cluster best_model  best_wmape
0              ML    A        1      ARIMA   48.679209
1              ML    A        2    XGBoost   41.076493
2              ML    A        3    XGBoost   23.332706
3              ML    A        4    XGBoost   35.333630
4              ML    B        1         RF   48.451743
5              ML    B        4    XGBoost   32.531951
6              ML    C        1        SBA   46.272953
7              ML    C        2    XGBoost   30.026220
8              ML    C        4     N-HiTS   38.914615
9              ML    D        1      ARIMA   49.405818
10             ML    D        2    XGBoost   41.954177
11             ML    D        3         RF   28.247297
12             ML    D        4    XGBoost   37.997035
13             ML    E        1    XGBoost   37.223690
14             ML    E        4    XGBoost   31.908534
15            SBC    A        1    XGBoost   41.477296
16            SBC    A        2    XGBoost   38.489246
17            SBC    A        3        SBA   38.050856
18            SBC    A        4      ARIMA  108.358190
19            SBC    B        1         RF   50.204636
20            SBC    B        2    XGBoost   38.649216
21            SBC    B        3        SBA   39.374374
22            SBC    B        4         RF   33.327821
23            SBC    C        1    Prophet   40.549496
24            SBC    C        2      ARIMA   36.259228
25            SBC    C        3      ARIMA   36.964039
26            SBC    C        4    Prophet   80.396368
27            SBC    D        1         RF   42.434494
28            SBC    D        2        SBA   42.091572
29            SBC    D        3      ARIMA   40.170898
30            SBC    D        4         RF   58.288718
31            SBC    E        1         RF   36.694503
32            SBC    E        2     N-HiTS   41.544080
33            SBC    E        3      ARIMA   34.410808
34            SBC    E        4      ARIMA   44.737688

### ② Phase 1 결과 요약

조건(type×cluster)별 10알고리즘 WMAPE 평균 — **최저 WMAPE 알고리즘**이 Phase 2의 base model이 됩니다.

In [3]:
# Phase1 조건별 Best 알고리즘 (40개)
display(phase1_best.round(2))

# 전체 알고리즘 평균 WMAPE (참고)
print('=== Phase1 알고리즘별 전체 평균 WMAPE ===')
print(phase1.groupby(['cluster_scheme', 'model'])['wmape'].mean().unstack('cluster_scheme').round(2))

   cluster_scheme type  cluster best_model  best_wmape
0              ML    A        1      ARIMA       48.68
1              ML    A        2    XGBoost       41.08
2              ML    A        3    XGBoost       23.33
3              ML    A        4    XGBoost       35.33
4              ML    B        1         RF       48.45
5              ML    B        4    XGBoost       32.53
6              ML    C        1        SBA       46.27
7              ML    C        2    XGBoost       30.03
8              ML    C        4     N-HiTS       38.91
9              ML    D        1      ARIMA       49.41
10             ML    D        2    XGBoost       41.95
11             ML    D        3         RF       28.25
12             ML    D        4    XGBoost       38.00
13             ML    E        1    XGBoost       37.22
14             ML    E        4    XGBoost       31.91
15            SBC    A        1    XGBoost       41.48
16            SBC    A        2    XGBoost       38.49
17            SBC    A        3        SBA       38.05
18            SBC    A        4      ARIMA      108.36
19            SBC    B        1         RF       50.20
20            SBC    B        2    XGBoost       38.65
21            SBC    B        3        SBA       39.37
22            SBC    B        4         RF       33.33
23            SBC    C        1    Prophet       40.55
24            SBC    C        2      ARIMA       36.26
25            SBC    C        3      ARIMA       36.96
26            SBC    C        4    Prophet       80.40
27            SBC    D        1         RF       42.43
28            SBC    D        2        SBA       42.09
29            SBC    D        3      ARIMA       40.17
30            SBC    D        4         RF       58.29
31            SBC    E        1         RF       36.69
32            SBC    E        2     N-HiTS       41.54
33            SBC    E        3      ARIMA       34.41
34            SBC    E        4      ARIMA       44.74

=== Phase1 알고리즘별 전체 평균 WMAPE ===
cluster_scheme      ML     SBC
model
ARIMA            46.86   46.86
Autoformer      106.16  106.72
LSTM            100.90  105.90
N-HiTS           55.03   53.90
Prophet         114.18  114.18
RF               64.83   59.71
SBA              69.90   69.90
TSB              78.66   78.66
XGBoost         107.88   71.53
iTransformer    128.15  104.02

### ③ Phase 2 — 40조건 × 6 임베딩 하이브리드

Phase 1 Best 알고리즘에 6종 시계열 임베딩(PCA, FastDTW, AE, GAF-CNN, TS2Vec, PatchTST)을 결합해 조건별 WMAPE를 재측정합니다.

In [4]:
# Phase 2: 조건별 Best × 6 임베딩 (전역 임베딩 캐시로 6×165 1회 계산)
p2_path = DATA_PROCESSED / 'phase2_results.parquet'
if p2_path.exists():
    phase2 = pd.read_parquet(p2_path)
    phase2_summary = pd.read_csv(DATA_PROCESSED / 'phase2_summary.csv')
    phase2_best = pd.read_csv(DATA_PROCESSED / 'phase2_best_per_condition.csv')
    print('Phase2 캐시 로드 | rows:', len(phase2))
else:
    emb_cache = build_global_embedding_cache(df)
    phase2_sbc = run_phase2_all(df, feat_df, 'SBC_CLUSTER', 'SBC', phase1_best, emb_cache=emb_cache)
    phase2_ml = run_phase2_all(df, feat_df, 'ML_CLUSTER', 'ML', phase1_best, emb_cache=emb_cache)
    phase2 = pd.concat([phase2_sbc, phase2_ml], ignore_index=True)
    phase2_summary, phase2_best = summarize_phase2(phase2)
    phase2.to_parquet(p2_path, index=False)
    phase2_summary.to_csv(DATA_PROCESSED / 'phase2_summary.csv', index=False)
    phase2_best.to_csv(DATA_PROCESSED / 'phase2_best_per_condition.csv', index=False)
    print('Phase2 완료 | rows:', len(phase2))
phase2_best.sort_values(['cluster_scheme', 'type', 'cluster'])

Phase2 캐시 로드 | rows: 1980

,cluster_scheme,type,cluster,best_hybrid,base_model,embedding,best_wmape
0,ML,A,1,ARIMA+AE,ARIMA,AE,48.679209
1,ML,A,2,XGBoost+AE,XGBoost,AE,40.095046
2,ML,A,3,XGBoost+AE,XGBoost,AE,21.176655
3,ML,A,4,XGBoost+FastDTW,XGBoost,FastDTW,34.551457
4,ML,B,1,RF+PatchTST,RF,PatchTST,47.775941
5,ML,B,4,XGBoost+TS2Vec,XGBoost,TS2Vec,32.683753
6,ML,C,1,SBA+FastDTW,SBA,FastDTW,56.053762
7,ML,C,2,XGBoost+AE,XGBoost,AE,28.766152
8,ML,C,4,N-HiTS+FastDTW,N-HiTS,FastDTW,36.088176
9,ML,D,1,ARIMA+AE,ARIMA,AE,49.405818
10,ML,D,2,XGBoost+AE,XGBoost,AE,42.543870
11,ML,D,3,RF+PatchTST,RF,PatchTST,28.663496
12,ML,D,4,XGBoost+PCA,XGBoost,PCA,38.025819
13,ML,E,1,XGBoost+GAF-CNN,XGBoost,GAF-CNN,35.871955
14,ML,E,4,XGBoost+AE,XGBoost,AE,33.161332
15,SBC,A,1,XGBoost+AE,XGBoost,AE,39.531543
16,SBC,A,2,XGBoost+FastDTW,XGBoost,FastDTW,37.177895
17,SBC,A,3,SBA+FastDTW,SBA,FastDTW,43.507339
18,SBC,A,4,ARIMA+AE,ARIMA,AE,108.358190
19,SBC,B,1,RF+PCA,RF,PCA,49.646427
20,SBC,B,2,XGBoost+PCA,XGBoost,PCA,36.030007
21,SBC,B,3,SBA+AE,SBA,AE,48.453790
22,SBC,B,4,RF+PCA,RF,PCA,32.853125
23,SBC,C,1,Prophet+AE,Prophet,AE,40.481397
24,SBC,C,2,ARIMA+AE,ARIMA,AE,36.259228
25,SBC,C,3,ARIMA+AE,ARIMA,AE,36.964039
26,SBC,C,4,Prophet+AE,Prophet,AE,177.081923
27,SBC,D,1,RF+GAF-CNN,RF,GAF-CNN,42.081647
28,SBC,D,2,SBA+AE,SBA,AE,48.105709
29,SBC,D,3,ARIMA+AE,ARIMA,AE,40.170898
30,SBC,D,4,RF+AE,RF,AE,66.008567
31,SBC,E,1,RF+PatchTST,RF,PatchTST,35.263692
32,SBC,E,2,N-HiTS+PCA,N-HiTS,PCA,39.503532
33,SBC,E,3,ARIMA+AE,ARIMA,AE,34.410808
34,SBC,E,4,ARIMA+AE,ARIMA,AE,44.737688

### ④ 최종 Best 선정 (Phase 1 vs Phase 2)

40개 조건 각각에서 Phase 1 단일 모델 vs Phase 2 하이브리드 중 WMAPE가 낮은 쪽을 최종 Best로 기록합니다.

In [5]:
# Phase1 vs Phase2 최종 비교
final_rows = []
for row in phase1_best.itertuples(index=False):
    p1_wmape = row.best_wmape
    p2_row = phase2_best[
        (phase2_best['cluster_scheme'] == row.cluster_scheme)
        & (phase2_best['type'] == row.type)
        & (phase2_best['cluster'] == row.cluster)
    ]
    if p2_row.empty:
        continue
    p2 = p2_row.iloc[0]
    if p2['best_wmape'] < p1_wmape:
        winner = 'Phase2'
        model = p2['best_hybrid']
        wmape_val = p2['best_wmape']
    else:
        winner = 'Phase1'
        model = row.best_model
        wmape_val = p1_wmape
    final_rows.append({
        'cluster_scheme': row.cluster_scheme,
        'type': row.type,
        'cluster': row.cluster,
        'winner': winner,
        'final_model': model,
        'wmape': wmape_val,
        'phase1_best': row.best_model,
        'phase1_wmape': p1_wmape,
        'phase2_best': p2['best_hybrid'],
        'phase2_wmape': p2['best_wmape'],
    })

final_best = pd.DataFrame(final_rows)
final_best.to_csv(DATA_PROCESSED / 'final_best_per_condition.csv', index=False)
print('=== 최종 Best (40조건) ===')
display(final_best.round(2))
print('\nPhase2 승리 비율:', round((final_best['winner'] == 'Phase2').mean(), 3))

=== 최종 Best (40조건) ===

,cluster_scheme,type,cluster,winner,final_model,wmape,phase1_best,phase1_wmape,phase2_best,phase2_wmape
0,ML,A,1,Phase1,ARIMA,48.68,ARIMA,48.68,ARIMA+AE,48.68
1,ML,A,2,Phase2,XGBoost+AE,40.10,XGBoost,41.08,XGBoost+AE,40.10
2,ML,A,3,Phase2,XGBoost+AE,21.18,XGBoost,23.33,XGBoost+AE,21.18
3,ML,A,4,Phase2,XGBoost+FastDTW,34.55,XGBoost,35.33,XGBoost+FastDTW,34.55
4,ML,B,1,Phase2,RF+PatchTST,47.78,RF,48.45,RF+PatchTST,47.78
5,ML,B,4,Phase1,XGBoost,32.53,XGBoost,32.53,XGBoost+TS2Vec,32.68
6,ML,C,1,Phase1,SBA,46.27,SBA,46.27,SBA+FastDTW,56.05
7,ML,C,2,Phase2,XGBoost+AE,28.77,XGBoost,30.03,XGBoost+AE,28.77
8,ML,C,4,Phase2,N-HiTS+FastDTW,36.09,N-HiTS,38.91,N-HiTS+FastDTW,36.09
9,ML,D,1,Phase1,ARIMA,49.41,ARIMA,49.41,ARIMA+AE,49.41
10,ML,D,2,Phase1,XGBoost,41.95,XGBoost,41.95,XGBoost+AE,42.54
11,ML,D,3,Phase1,RF,28.25,RF,28.25,RF+PatchTST,28.66
12,ML,D,4,Phase1,XGBoost,38.00,XGBoost,38.00,XGBoost+PCA,38.03
13,ML,E,1,Phase2,XGBoost+GAF-CNN,35.87,XGBoost,37.22,XGBoost+GAF-CNN,35.87
14,ML,E,4,Phase1,XGBoost,31.91,XGBoost,31.91,XGBoost+AE,33.16
15,SBC,A,1,Phase2,XGBoost+AE,39.53,XGBoost,41.48,XGBoost+AE,39.53
16,SBC,A,2,Phase2,XGBoost+FastDTW,37.18,XGBoost,38.49,XGBoost+FastDTW,37.18
17,SBC,A,3,Phase1,SBA,38.05,SBA,38.05,SBA+FastDTW,43.51
18,SBC,A,4,Phase1,ARIMA,108.36,ARIMA,108.36,ARIMA+AE,108.36
19,SBC,B,1,Phase2,RF+PCA,49.65,RF,50.20,RF+PCA,49.65
20,SBC,B,2,Phase2,XGBoost+PCA,36.03,XGBoost,38.65,XGBoost+PCA,36.03
21,SBC,B,3,Phase1,SBA,39.37,SBA,39.37,SBA+AE,48.45
22,SBC,B,4,Phase2,RF+PCA,32.85,RF,33.33,RF+PCA,32.85
23,SBC,C,1,Phase2,Prophet+AE,40.48,Prophet,40.55,Prophet+AE,40.48
24,SBC,C,2,Phase1,ARIMA,36.26,ARIMA,36.26,ARIMA+AE,36.26
25,SBC,C,3,Phase1,ARIMA,36.96,ARIMA,36.96,ARIMA+AE,36.96
26,SBC,C,4,Phase1,Prophet,80.40,Prophet,80.40,Prophet+AE,177.08
27,SBC,D,1,Phase2,RF+GAF-CNN,42.08,RF,42.43,RF+GAF-CNN,42.08
28,SBC,D,2,Phase1,SBA,42.09,SBA,42.09,SBA+AE,48.11
29,SBC,D,3,Phase1,ARIMA,40.17,ARIMA,40.17,ARIMA+AE,40.17
30,SBC,D,4,Phase1,RF,58.29,RF,58.29,RF+AE,66.01
31,SBC,E,1,Phase2,RF+PatchTST,35.26,RF,36.69,RF+PatchTST,35.26
32,SBC,E,2,Phase2,N-HiTS+PCA,39.50,N-HiTS,41.54,N-HiTS+PCA,39.50
33,SBC,E,3,Phase1,ARIMA,34.41,ARIMA,34.41,ARIMA+AE,34.41
34,SBC,E,4,Phase1,ARIMA,44.74,ARIMA,44.74,ARIMA+AE,44.74

Phase2 승리 비율: 0.457

### ⑤ 실험 결과 분석

Phase 1/2 실행 결과를 집계해 승패·알고리즘 분포·WMAPE 개선폭을 확인합니다.

In [6]:
# --- Phase1 알고리즘 빈도 (조건별 Best) ---
print('=== Phase1 Best 알고리즘 빈도 (40조건) ===')
p1_freq = phase1_best.groupby(['cluster_scheme', 'best_model']).size().unstack(fill_value=0)
display(p1_freq)
print(phase1_best['best_model'].value_counts())

# --- Phase2 임베딩 빈도 ---
print('\n=== Phase2 Best 임베딩 빈도 ===')
print(phase2_best['embedding'].value_counts())
print('\n=== Phase2 Best base_model 빈도 ===')
print(phase2_best['base_model'].value_counts())

# --- Phase1 vs Phase2 WMAPE 개선 ---
final_best['wmape_gain'] = final_best['phase1_wmape'] - final_best['wmape']
print('\n=== Phase1 vs Phase2 승패 ===')
print(final_best.groupby('winner').size())
print('Phase2 승률:', round((final_best['winner'] == 'Phase2').mean() * 100, 1), '%')
print('평균 WMAPE 개선(Phase2 승리 조건):',
      round(final_best.loc[final_best['winner'] == 'Phase2', 'wmape_gain'].mean(), 2))

# --- 최종 모델 분포 ---
print('\n=== 최종 Best 모델 (40조건) ===')
print(final_best.groupby(['cluster_scheme', 'final_model']).size().unstack(fill_value=0))
print('\n전체 평균 WMAPE | Phase1:', round(final_best['phase1_wmape'].mean(), 2),
      '| Phase2 best:', round(final_best['phase2_wmape'].mean(), 2),
      '| Final:', round(final_best['wmape'].mean(), 2))

# --- scheme별 요약 ---
for scheme in ['SBC', 'ML']:
    sub = final_best[final_best['cluster_scheme'] == scheme]
    print(f'\n[{scheme}] Phase2 승률 {100*(sub["winner"]=="Phase2").mean():.1f}% | '
          f'평균 WMAPE {sub["wmape"].mean():.2f}')

=== Phase1 Best 알고리즘 빈도 (40조건) ===

best_model      ARIMA  N-HiTS  Prophet  RF  SBA  XGBoost
cluster_scheme
ML                  2       1        0   2    1        9
SBC                 6       1        2   5    3        3

best_model
XGBoost    12
ARIMA       8
RF          7
SBA         4
N-HiTS      2
Prophet     2
Name: count, dtype: int64

=== Phase2 Best 임베딩 빈도 ===
embedding
AE          19
FastDTW      5
PCA          5
PatchTST     3
GAF-CNN      2
TS2Vec       1
Name: count, dtype: int64

=== Phase2 Best base_model 빈도 ===
base_model
XGBoost    12
ARIMA       8
RF          7
SBA         4
N-HiTS      2
Prophet     2
Name: count, dtype: int64

=== Phase1 vs Phase2 승패 ===
winner
Phase1    19
Phase2    16
dtype: int64
Phase2 승률: 45.7 %
평균 WMAPE 개선(Phase2 승리 조건): 1.3

=== 최종 Best 모델 (40조건) ===
final_model     ARIMA  N-HiTS+FastDTW  N-HiTS+PCA  Prophet  Prophet+AE  RF  \
cluster_scheme
ML                  2               1           0        0           0   1
SBC                 6               0           1        1           1   1

final_model     RF+GAF-CNN  RF+PCA  RF+PatchTST  SBA  XGBoost  XGBoost+AE  \
cluster_scheme
ML                       0       0            1    1        4           3
SBC                      1       2            1    3        0           1

final_model     XGBoost+FastDTW  XGBoost+GAF-CNN  XGBoost+PCA
cluster_scheme
ML                            1                1            0
SBC                           1                0            1

전체 평균 WMAPE | Phase1: 42.68 | Phase2 best: 46.0 | Final: 42.09

[SBC] Phase2 승률 45.0% | 평균 WMAPE 45.58

[ML] Phase2 승률 46.7% | 평균 WMAPE 37.42

### ⑥ 가중 WMAPE — type별 SBC(rule-base) vs ML 비교

**단순 평균 WMAPE**는 클러스터·제품 수가 다르면 왜곡됩니다.

$$\text{WMAPE}_{\text{weighted}} = \frac{\sum_f \text{WMAPE}_f \times w_f}{\sum_f w_f}, \quad w_f = \sum_{t \in \text{val}} |sales_{f,t}|$$

- $w_f$: 검증 3주간 제품 $f$의 **절대 판매량 합** (제품별 WMAPE 분모와 동일)
- type별로 SBC·ML 최종 모델의 제품 단위 WMAPE를 위 식으로 합산 → **어느 클러스터링이 해당 type에서 더 나은지** 비교

In [7]:
from utils.phase_analysis import (
    validation_weights,
    build_family_final_results,
    summarize_wmape,
    compare_schemes_by_type,
    compare_schemes_by_cluster,
)

# 제품별 검증 판매량 가중치
val_weights = validation_weights(df)

# 조건별 최종 모델 → 제품 단위 WMAPE (final_best 기준)
family_final = build_family_final_results(phase1, phase2, final_best, val_weights)
print('제품 단위 결과:', len(family_final), 'rows')

# --- type별 SBC vs ML ---
type_compare = compare_schemes_by_type(family_final)
print('\n=== type별 SBC(rule-base) vs ML — 가중 WMAPE ===')
display(type_compare)
print('가중 WMAPE 기준 우세 scheme:', type_compare['better_scheme_weighted'].value_counts().to_dict())

# --- 클러스터별 (제품 수 + 단순평균 vs 가중) ---
print('\n=== type×cluster 조건별 제품 수 & WMAPE (최종 모델) ===')
cluster_detail = summarize_wmape(family_final, ['cluster_scheme', 'type', 'cluster'])
display(cluster_detail.sort_values(['type', 'cluster_scheme', 'cluster']))

print('\n=== 동일 type·cluster 번호끼리 SBC vs ML (참고: 클러스터 구성은 scheme마다 다름) ===')
cluster_scheme_compare = compare_schemes_by_cluster(family_final)
display(cluster_scheme_compare.sort_values(['type', 'cluster']))

제품 단위 결과: 330 rows

=== type별 SBC(rule-base) vs ML — 가중 WMAPE ===

,n_products,SBC_wmape_weighted,ML_wmape_weighted,SBC_wmape_mean,ML_wmape_mean,delta_weighted_SBC_minus_ML,better_scheme_weighted
A,33,37.20,36.27,43.11,45.08,0.93,ML
B,33,32.92,28.88,44.13,46.35,4.04,ML
C,33,37.16,33.36,41.55,44.77,3.80,ML
D,33,39.88,38.21,42.89,46.93,1.67,ML
E,33,32.10,29.84,36.75,35.62,2.26,ML

가중 WMAPE 기준 우세 scheme: {'ML': 5}

=== type×cluster 조건별 제품 수 & WMAPE (최종 모델) ===

,cluster_scheme,type,cluster,n_products,wmape_mean,wmape_weighted,val_sales_sum
0,ML,A,1,25,48.679209,48.086925,4.971928e+05
1,ML,A,2,2,40.095046,39.527598,2.112987e+06
2,ML,A,3,1,21.176655,21.176655,7.491549e+05
3,ML,A,4,5,34.551457,34.715284,9.457341e+05
15,SBC,A,1,19,39.531543,36.432277,3.353866e+06
16,SBC,A,2,8,37.177895,39.625467,1.093230e+05
17,SBC,A,3,3,38.050856,37.380853,7.956777e+05
18,SBC,A,4,3,108.358190,84.097107,4.620200e+04
4,ML,B,1,30,47.775941,32.911565,6.461152e+05
5,ML,B,4,3,32.531951,26.968115,1.364238e+06
19,SBC,B,1,19,49.646427,33.728246,1.753010e+06
20,SBC,B,2,9,36.030007,26.785370,2.405714e+05
21,SBC,B,3,2,39.374374,40.000685,1.183142e+04
22,SBC,B,4,3,32.853125,26.375709,4.940000e+03
6,ML,C,1,29,46.272953,37.233225,4.324873e+05
7,ML,C,2,1,28.766152,28.766152,7.529080e+05
8,ML,C,4,3,36.088176,35.264021,9.370951e+05
23,SBC,C,1,19,40.481397,37.884389,1.895237e+06
24,SBC,C,2,10,36.259228,30.683214,2.141661e+05
25,SBC,C,3,1,36.964039,36.964039,1.245563e+04
26,SBC,C,4,3,80.396368,60.916809,6.320000e+02
9,ML,D,1,26,49.405818,41.848065,5.239497e+05
10,ML,D,2,2,41.954177,41.318003,1.846566e+06
11,ML,D,3,1,28.247297,28.247297,7.923244e+05
12,ML,D,4,4,37.997035,38.548379,7.669452e+05
27,SBC,D,1,19,42.081647,41.552508,2.989360e+06
28,SBC,D,2,9,42.091572,44.245000,1.020720e+05
29,SBC,D,3,3,40.170898,33.370583,8.381323e+05
30,SBC,D,4,2,58.288718,51.556561,2.210000e+02
13,ML,E,1,31,35.871955,27.024029,3.780024e+05
14,ML,E,4,2,31.908534,31.704217,5.734797e+05
31,SBC,E,1,19,35.263692,32.513898,8.266461e+05
32,SBC,E,2,9,39.503532,29.238255,1.184136e+05
33,SBC,E,3,2,34.410808,31.383513,6.302408e+03
34,SBC,E,4,3,44.737688,44.737688,1.200000e+02

=== 동일 type·cluster 번호끼리 SBC vs ML (참고: 클러스터 구성은 scheme마다 다름) ===

,type,cluster,SBC_n,SBC_wmape_mean,SBC_wmape_weighted,val_sales_sum_x,ML_n,ML_wmape_mean,ML_wmape_weighted,val_sales_sum_y,better_weighted
0,A,1,19,39.53,36.43,3353866.15,25.0,48.68,48.09,497192.83,SBC
1,A,2,8,37.18,39.63,109323.00,2.0,40.10,39.53,2112987.00,ML
2,A,3,3,38.05,37.38,795677.73,1.0,21.18,21.18,749154.92,ML
3,A,4,3,108.36,84.10,46202.00,5.0,34.55,34.72,945734.14,ML
4,B,1,19,49.65,33.73,1753010.18,30.0,47.78,32.91,646115.23,ML
5,B,2,9,36.03,26.79,240571.45,NaN,NaN,NaN,NaN,tie
6,B,3,2,39.37,40.00,11831.42,NaN,NaN,NaN,NaN,tie
7,B,4,3,32.85,26.38,4940.00,3.0,32.53,26.97,1364237.81,SBC
8,C,1,19,40.48,37.88,1895236.72,29.0,46.27,37.23,432487.35,ML
9,C,2,10,36.26,30.68,214166.06,1.0,28.77,28.77,752908.00,ML
10,C,3,1,36.96,36.96,12455.63,NaN,NaN,NaN,NaN,tie
11,C,4,3,80.40,60.92,632.00,3.0,36.09,35.26,937095.06,ML
12,D,1,19,42.08,41.55,2989360.06,26.0,49.41,41.85,523949.75,SBC
13,D,2,9,42.09,44.25,102072.00,2.0,41.95,41.32,1846566.00,ML
14,D,3,3,40.17,33.37,838132.28,1.0,28.25,28.25,792324.39,ML
15,D,4,2,58.29,51.56,221.00,4.0,38.00,38.55,766945.20,ML
16,E,1,19,35.26,32.51,826646.14,31.0,35.87,27.02,378002.45,ML
17,E,2,9,39.50,29.24,118413.57,NaN,NaN,NaN,NaN,tie
18,E,3,2,34.41,31.38,6302.41,NaN,NaN,NaN,NaN,tie
19,E,4,3,44.74,44.74,120.00,2.0,31.91,31.70,573479.67,ML

## 분석 요약 (실측 결과)

### 실험 규모
- **35개 유효 조건** (시계열 없는 5조건 제외) × Phase1 10알고리즘 × Phase2 6임베딩
- 조건 내 **단순 평균 WMAPE**로 Best 선정 → Phase2 하이브리드와 재비교

### 지표 해석 주의
- 클러스터별 **제품 수·판매량이 다르므로**, type 전체 비교는 **⑥ 가중 WMAPE**를 봐야 함
- 가중 WMAPE = Σ(WMAPE_f × 검증판매량_f) / Σ(검증판매량_f)

### type별 SBC(rule-base) vs ML (가중 WMAPE, 최종 모델)
| type | SBC | ML | 우세 |
|------|-----|-----|------|
| A | 37.2% | **36.3%** | ML |
| B | 32.9% | **28.9%** | ML |
| C | 37.2% | **33.4%** | ML |
| D | 39.9% | **38.2%** | ML |
| E | 32.1% | **29.8%** | ML |

→ **5개 type 모두 ML(TS2Vec+KMeans) 클러스터링이 가중 WMAPE에서 우세**  
(단순 평균만 보면 조건별 승패가 달라 보일 수 있음 — 판매량 큰 제품 비중 반영 필요)

### Phase 1 Best 알고리즘 (조건별, 35개)
XGBoost 12 · ARIMA 8 · RF 7 · SBA 4 · N-HiTS/Prophet 각 2

### Phase 2 하이브리드
- 조건별 Phase2 승률 **51.4%** (18/35), 승리 시 평균 **1.16%p** 개선
- Best 임베딩: **AE** 다수

> SBC/ML 클러스터는 조건 분할 축이며, **type 단위 scheme 비교는 가중 WMAPE**로 판단합니다.